2022-02-08 08:18:56,568 INFO    MainThread:408 [wandb_setup.py:_flush():69] setting env: {}
2022-02-08 08:18:56,569 INFO    MainThread:408 [wandb_setup.py:_flush():69] setting login settings: {}
2022-02-08 08:18:56,569 INFO    MainThread:408 [wandb_init.py:_log_setup():336] Logging user logs to /workspace/graph-neural-pde/src/wandb/run-20220208_081856-alpha=2.0_T=0.1/logs/debug.log
2022-02-08 08:18:56,569 INFO    MainThread:408 [wandb_init.py:_log_setup():337] Logging internal logs to /workspace/graph-neural-pde/src/wandb/run-20220208_081856-alpha=2.0_T=0.1/logs/debug-internal.log
2022-02-08 08:18:56,570 INFO    MainThread:408 [wandb_init.py:init():369] calling init triggers
2022-02-08 08:18:56,570 INFO    MainThread:408 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2022-02-08 08:18:56,570 INFO    MainThread:408 [wandb_init.py:init():418] starting backend
2022-02-08 08:18:56,570 INFO    MainThread:408 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-08 08:18:56,600 WARNING MainThread:408 [wandb_init.py:init():764] interrupted
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 744, in init
    run = wi.init()
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 421, in init
    backend.ensure_launched()
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/backend/backend.py", line 88, in ensure_launched
    self.record_q = self._multiprocessing.Queue()
  File "/opt/conda/lib/python3.6/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/opt/conda/lib/python3.6/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/opt/conda/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/opt/conda/lib/python3.6/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/opt/conda/lib/python3.6/multiprocessing/synchronize.py", line 80, in __init__
    register(self._semlock.name)
  File "/opt/conda/lib/python3.6/multiprocessing/semaphore_tracker.py", line 83, in register
    self._send('REGISTER', name)
  File "/opt/conda/lib/python3.6/multiprocessing/semaphore_tracker.py", line 90, in _send
    self.ensure_running()
  File "/opt/conda/lib/python3.6/multiprocessing/semaphore_tracker.py", line 71, in ensure_running
    pid = util.spawnv_passfds(exe, args, fds_to_pass)
  File "/opt/conda/lib/python3.6/multiprocessing/util.py", line 417, in spawnv_passfds
    False, False, None)
KeyboardInterrupt
