2022-04-13 17:42:13,873 INFO    MainThread:8559 [wandb_setup.py:_flush():75] Loading settings from /home/administrator/.config/wandb/settings
2022-04-13 17:42:13,873 INFO    MainThread:8559 [wandb_setup.py:_flush():75] Loading settings from /home/administrator/hieu/graph-neural-pde/src/wandb/settings
2022-04-13 17:42:13,873 INFO    MainThread:8559 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-13 17:42:13,873 INFO    MainThread:8559 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/test_multiple_planetoid_splits.py', 'program': 'test_multiple_planetoid_splits.py'}
2022-04-13 17:42:13,873 INFO    MainThread:8559 [wandb_init.py:_log_setup():438] Logging user logs to /home/administrator/hieu/graph-neural-pde/src/wandb/run-20220413_174213-9_tbl_1_lr_deepgrand_pubmed/logs/debug.log
2022-04-13 17:42:13,874 INFO    MainThread:8559 [wandb_init.py:_log_setup():439] Logging internal logs to /home/administrator/hieu/graph-neural-pde/src/wandb/run-20220413_174213-9_tbl_1_lr_deepgrand_pubmed/logs/debug-internal.log
2022-04-13 17:42:13,874 INFO    MainThread:8559 [wandb_init.py:init():472] calling init triggers
2022-04-13 17:42:13,874 INFO    MainThread:8559 [wandb_init.py:init():476] wandb.init called with sweep_config: {}
config: {}
2022-04-13 17:42:13,874 INFO    MainThread:8559 [wandb_init.py:init():525] starting backend
2022-04-13 17:42:13,875 INFO    MainThread:8559 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-13 17:42:13,905 INFO    MainThread:8559 [backend.py:ensure_launched():219] starting backend process...
2022-04-13 17:42:13,917 INFO    MainThread:8559 [backend.py:ensure_launched():225] started backend process with pid: 8681
2022-04-13 17:42:13,919 INFO    MainThread:8559 [wandb_init.py:init():534] backend started and connected
2022-04-13 17:42:13,930 INFO    MainThread:8559 [wandb_init.py:init():598] updated telemetry
2022-04-13 17:42:13,971 INFO    MainThread:8559 [wandb_init.py:init():629] communicating run to backend with 30 second timeout
2022-04-13 17:42:14,670 WARNING MainThread:8559 [wandb_init.py:init():1017] interrupted
Traceback (most recent call last):
  File "/home/administrator/anaconda3/envs/grand/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 996, in init
    run = wi.init()
  File "/home/administrator/anaconda3/envs/grand/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 630, in init
    run_result = backend.interface.communicate_run(run, timeout=30)
  File "/home/administrator/anaconda3/envs/grand/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/administrator/anaconda3/envs/grand/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 323, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/administrator/anaconda3/envs/grand/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 225, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/administrator/anaconda3/envs/grand/lib/python3.7/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/administrator/anaconda3/envs/grand/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/home/administrator/anaconda3/envs/grand/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
